usb: misc: onboard_usb_dev: introduce new config symbol for Microchip usb5744 SMBus support
Introduce new kernel config symbol for Microchip usb5744 SMBus programming
support. This is done to describe the dependency on I2C kernel support and
fix below build issues with when USB_ONBOARD_DEV=y and CONFIG_I2C=m.

riscv64-linux-ld: drivers/usb/misc/onboard_usb_dev.o:
undefined reference to `i2c_find_device_by_fwnode'
drivers/usb/misc/onboard_usb_dev.c:408:(.text+0xb24): undefined
reference to `i2c_smbus_write_block_data'
<snip>

Signed-off-by: Radhey Shyam Pandey <radhey.shyam.pandey@amd.com>